---
- hosts: all
  become: true
  tasks:
    - name: install nfs client
      action: apt pkg=nfs-common state=present
      tags: -nfs

    - name: ensure nfs service is running (Ubuntu)
      action: service name={{item}} state=started
      tags:
        - nfs
      with_items:
        - nfs-kernel-server
